#!/usr/bin/env bash
#
# BT Panel — Debian 12/13 one-shot installer.
#
# Installs Node.js 22, MariaDB, Nginx and Certbot, deploys the panel to
# /opt/bt-panel, and serves it through Nginx on the given domain. The app is
# bound to 127.0.0.1:3001 so it is only reachable through the reverse proxy.
#
# Usage:
#   sudo bash deploy/setup-debian.sh panel.example.com
#
# Point a DNS A/AAAA record at this server before the first run if you want
# HTTPS on that pass; otherwise the panel is served over HTTP and you can
# re-run the script later to obtain a certificate.
#
# Re-running the script updates the deployment in place (secrets are reused)
# and is safe.

set -euo pipefail

DOMAIN="${1:-}"
APP_USER="bt-panel"
APP_DIR="/opt/bt-panel"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DB_NAME="btpanel"
DB_USER="btpanel"
NODE_MAJOR="22"
SERVICE="bt-panel"

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }

[[ ${EUID:-$(id -u)} -eq 0 ]] || die "Run as root: sudo bash deploy/setup-debian.sh ${DOMAIN:-panel.example.com}"
[[ -n "$DOMAIN" ]] || die "Usage: sudo bash deploy/setup-debian.sh panel.example.com"
command -v apt-get >/dev/null 2>&1 || die "This installer targets Debian/Ubuntu (apt-get not found)."

export DEBIAN_FRONTEND=noninteractive

# ---------------------------------------------------------------------------
# 1. System packages
# ---------------------------------------------------------------------------
log "Installing system packages"
apt-get update -y
apt-get install -y --no-install-recommends \
  ca-certificates curl gnupg rsync git build-essential python3 \
  mariadb-server nginx certbot python3-certbot-nginx

# ---------------------------------------------------------------------------
# 2. Node.js 22
# ---------------------------------------------------------------------------
if ! command -v node >/dev/null 2>&1 || \
   [[ "$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null)" != "$NODE_MAJOR" ]]; then
  log "Installing Node.js ${NODE_MAJOR}"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
  apt-get install -y nodejs
fi
log "Using Node $(node -v) / npm $(npm -v)"

# ---------------------------------------------------------------------------
# 3. MariaDB
# ---------------------------------------------------------------------------
log "Ensuring MariaDB is running"
systemctl enable --now mariadb

# Reuse secrets from a previous install so upgrades do not break the DB.
DB_PASSWORD=""
JWT_SECRET=""
if [[ -f "$APP_DIR/.env" ]]; then
  DB_PASSWORD="$(grep -oP '^DATABASE_URL=mysql://[^:]+:\K[^@]+' "$APP_DIR/.env" || true)"
  JWT_SECRET="$(grep -oP '^JWT_SECRET=\K.*' "$APP_DIR/.env" || true)"
fi
if [[ -z "$DB_PASSWORD" ]]; then
  DB_PASSWORD="$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
fi
if [[ -z "$JWT_SECRET" ]]; then
  JWT_SECRET="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
fi

log "Creating database '${DB_NAME}' and user '${DB_USER}'"
mariadb <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASSWORD}';
ALTER USER '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

# ---------------------------------------------------------------------------
# 4. Application user + source sync
# ---------------------------------------------------------------------------
log "Creating service user '${APP_USER}'"
id -u "$APP_USER" >/dev/null 2>&1 || \
  useradd --system --home "$APP_DIR" --shell /usr/sbin/nologin "$APP_USER"

mkdir -p "$APP_DIR"
if [[ "$SRC_DIR" != "$APP_DIR" ]]; then
  log "Syncing application from ${SRC_DIR} to ${APP_DIR}"
  rsync -a --delete \
    --exclude '.git' \
    --exclude 'node_modules' \
    --exclude '.next' \
    --exclude '.env' \
    --exclude 'data' \
    --exclude 'mpanel' \
    --exclude 'server-panel' \
    --exclude 'public/uploads' \
    "$SRC_DIR"/ "$APP_DIR"/
fi

# ---------------------------------------------------------------------------
# 5. Environment file
# ---------------------------------------------------------------------------
log "Writing ${APP_DIR}/.env (mode 0600)"
cat > "$APP_DIR/.env" <<EOF
# Generated by deploy/setup-debian.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do not commit this file.
NODE_ENV=production
PORT=3001
DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@127.0.0.1:3306/${DB_NAME}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d
PANEL_NAME="BT Panel"
PUBLIC_BASE_URL=
COOKIE_SECURE=false
EOF
chmod 600 "$APP_DIR/.env"
chown "$APP_USER:$APP_USER" "$APP_DIR/.env"

# ---------------------------------------------------------------------------
# 6. Install + build
# ---------------------------------------------------------------------------
log "Installing dependencies and building the panel"
chown -R "$APP_USER:$APP_USER" "$APP_DIR"
sudo -u "$APP_USER" bash -c "cd '$APP_DIR' && npm ci --no-audit --no-fund && npm run build"

# ---------------------------------------------------------------------------
# 7. systemd service
# ---------------------------------------------------------------------------
log "Installing systemd unit ${SERVICE}.service"
cat > "/etc/systemd/system/${SERVICE}.service" <<EOF
[Unit]
Description=BT Panel (Next.js)
After=network-online.target mariadb.service
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${APP_DIR}/.env
Environment=NODE_ENV=production
ExecStart=/usr/bin/npm start -- -H 127.0.0.1 -p 3001
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "$SERVICE"
systemctl restart "$SERVICE"

# ---------------------------------------------------------------------------
# 8. Nginx reverse proxy
# ---------------------------------------------------------------------------
log "Configuring Nginx for ${DOMAIN}"
cat > "/etc/nginx/sites-available/${SERVICE}" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
    }
}
EOF
ln -sf "/etc/nginx/sites-available/${SERVICE}" "/etc/nginx/sites-enabled/${SERVICE}"
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

# ---------------------------------------------------------------------------
# 9. HTTPS (best effort — needs DNS pointed at this server)
# ---------------------------------------------------------------------------
TLS=0
log "Requesting an HTTPS certificate for ${DOMAIN}"
if certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos --no-eff-email \
     -m "admin@${DOMAIN}" --redirect; then
  TLS=1
else
  warn "certbot could not issue a certificate. Serving over HTTP for now;"
  warn "point DNS at this server and re-run to enable HTTPS."
fi

if [[ "$TLS" -eq 1 ]]; then
  PUBLIC_BASE_URL="https://${DOMAIN}"
  COOKIE_SECURE="true"
else
  PUBLIC_BASE_URL="http://${DOMAIN}"
  COOKIE_SECURE="false"
fi
sed -i -e "s|^PUBLIC_BASE_URL=.*|PUBLIC_BASE_URL=${PUBLIC_BASE_URL}|" \
       -e "s|^COOKIE_SECURE=.*|COOKIE_SECURE=${COOKIE_SECURE}|" \
       "$APP_DIR/.env"
systemctl restart "$SERVICE"

# ---------------------------------------------------------------------------
# 10. Firewall (only if ufw is already active)
# ---------------------------------------------------------------------------
if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
  log "Opening firewall for SSH and Nginx"
  ufw allow OpenSSH >/dev/null 2>&1 || true
  ufw allow 'Nginx Full' >/dev/null 2>&1 || true
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
log "Installation complete"
echo
echo "  URL:        ${PUBLIC_BASE_URL}/register"
echo "  Service:    systemctl status ${SERVICE}"
echo "  Logs:       journalctl -u ${SERVICE} -f"
echo "  Env file:   ${APP_DIR}/.env (mode 0600)"
echo "  Database:   ${DB_NAME} on 127.0.0.1:3306 (user ${DB_USER})"
echo
echo "Open ${PUBLIC_BASE_URL}/register — the first account becomes the owner."
echo "MariaDB and port 3001 are private; only Nginx (80/443) is public."
